using Printf

"""


Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Using a naive approach
# Look for stupid 
limit = Int64(4E6)
# limit = 10
#fibSum  = Int64(0)

fib1 = 1
fib2 = 1
fib = 0
fibSum=0
while fib < limit
     fib = fib1 + fib2
     fib2 = fib1
     fib1 = fib
     if fib % 2 == 0
        fibSum += fib
     end
end

@printf("fibSum: %d\n",fibSum)